In [2]:
import numpy as np

### Arrays

In [7]:
# Scalar
s = np.array(5)

In [10]:
# vector
v = np.array([1,2,3])
v.shape

(3,)

In [13]:
# Matrices
m = np.array([[1,2],[4,5],[7,8]])
m.shape

(3, 2)

In [27]:
# tensors
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[18]]]])
t.shape

(3, 3, 2, 1)

### Reshape

In [28]:
v.shape

(3,)

In [29]:
x = v.reshape(1,3)
x

array([[1, 2, 3]])

### Matrix Multiplication

In [32]:
m1 = m
m2 = np.array([[2,3],[5,6]])

print("m1 shape : ",m1.shape, "m2.shape : ",m2.shape)

m1 shape :  (3, 2) m2.shape :  (2, 2)


In [34]:
m = np.matmul(m1,m2)
print(m.shape)
m

(3, 2)


array([[12, 15],
       [33, 42],
       [54, 69]])

### Transpose

In [36]:
m_t = m.T
print(m_t.shape)
m_t

(2, 3)


array([[12, 33, 54],
       [15, 42, 69]])

NOTE : The transpose matrix m_t and m share the same copy of data. That means changing values in any one of the matrices will update theo other one too.

In [39]:
m_t[0][0] = 100
print(m_t)
print(m)

[[100  33  54]
 [ 15  42  69]]
[[100  15]
 [ 33  42]
 [ 54  69]]


In [42]:
x = np.amin(m)
x

15

In [4]:
s = 1/(1+np.exp(-2))
s

0.8807970779778823